config/routes.rb
Audiohub::Application.routes.draw do

  get "friendships/create"
  get "friendships/destroy"
  devise_for :users
  resources :users
  resources :audios
  resources :friendships

  get "home/index"

  root to: 'home#index'

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  belongs_to :user

  has_attached_file :source
  validates_attachment_presence :source
#  validates_attachment_content_type :source, :content_type => [ 'application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3' ]
  validates_attachment_size :source, :less_than => 100.megabytes



  include AASM

  aasm do
    state :pending, :initial => true
    state :converting
    state :converted, :enter => :update_attributes
    state :error
    
    event :convert do
      transitions :from => :pending, :to => :converting
    end
    
    event :converted do
      transitions :from => :converting, :to => :converted
    end
    
    event :failed do
      transitions :from => :converting, :to => :error
    end
  end


  protected
 
  def update_attributes
    stripped_name = source.original_filename.chomp(File.extname(source.original_filename))

    update_attribute(:source_file_name, "#{ stripped_name }.mp3")
    update_attribute(:source_content_type, "audio/mp3")
    update_attribute(:source_file_size, File.size(source.path))
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :audios, dependent: :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.search(search)
    if search
      where('email LIKE ?', "%#{search}%") ||
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit :name, :email, :password, :password_confirmation
      end
    end
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_audio, only: [:show, :destroy]

  def index
    if params[:friend_id]
      @audios = current_user.friends.find_by_id(params[:friend_id]).audios.all
    else
      @audios = current_user.audios.all
    end
  end

  def new
  	@audio = current_user.audios.new
  end

  def create
  	@audio = current_user.audios.new(audio_params)
    if @audio.save
      ConversionWorker.perform_async(@audio.id)
      redirect_to root_url, notice: 'Audio has been uploaded'
    else
      render action: 'new'
    end
  end

  def show
  end

  def destroy
    @audio.destroy
    redirect_to root_url, notice: 'Audio has been deleted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio
      @audio = current_user.audios.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_params
      params.require(:audio).permit(:source)
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
  	@friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  	@audios = current_user.audios.all
  	@friends = current_user.friends & current_user.inverse_friends
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.search(params[:search])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/audios/index.html.haml
.page-header
  %h1=t '.title', :default => Audio.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= Audio.human_attribute_name(:id)
      %th= Audio.human_attribute_name(:source_content_type)
      %th= Audio.human_attribute_name(:source_file_name)
      %th= Audio.human_attribute_name(:source_file_size)
      %th= Audio.human_attribute_name(:aasm_state)
      %th= Audio.human_attribute_name(:created_at)
      %th= Audio.human_attribute_name(:updated_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @audios.each do |audio|
      %tr
        %td= link_to audio.id, audio_path(audio)
        %td= audio.source_content_type
        %td= audio.source_file_name
        %td= audio.source_file_size
        %td= audio.aasm_state
        %td= audio.created_at
        %td= audio.updated_at
        %td
          = link_to "Download", audio.source.url(:original, false), :class => 'btn btn-mini btn-primary'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), audio_path(audio), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'


= link_to t('.new', :default => t("helpers.links.new")), new_audio_path, :class => 'btn btn-primary'

app/views/audios/new.html.haml
%h2 New Audio
= form_for @audio, :html => { :multipart => true } do |f|
  %div
    = f.label :source
    %br/
    = f.file_field :source
  %div= f.submit "Submit"
= link_to "Back", audios_path

app/views/audios/show.html.haml
- model_class = Audio
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:aasm_state) + ':'
  %br
  = @audio.aasm_state
%p
  %strong= model_class.human_attribute_name(:created_at) + ':'
  %br
  = @audio.created_at
%p
  %strong= model_class.human_attribute_name(:updated_at) + ':'
  %br
  = @audio.updated_at
%p
  %strong= model_class.human_attribute_name(:source_file_name) + ':'
  %br
  = @audio.source_file_name
%p
  %strong= model_class.human_attribute_name(:source_content_type) + ':'
  %br
  = @audio.source_content_type
%p
  %strong= model_class.human_attribute_name(:source_file_size) + ':'
  %br
  = @audio.source_file_size
%p
  %strong= model_class.human_attribute_name(:source_updated_at) + ':'
  %br
  = @audio.source_updated_at

= link_to t('.back', :default => t("helpers.links.back")), audios_path, :class => 'btn'
= link_to t('.destroy', :default => t("helpers.links.destroy")), audio_path(@audio), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/home/index.html.haml
= render template: "audios/index"

%h1 Friends
%ul
  - for friend in @friends
    %li
      =h friend.name
      = link_to "audios", audios_path(:friend_id => friend)

= form_tag users_path, method: :get do
  = text_field_tag :search
  = submit_tag 'Find Friends', name: nil

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Audiohub"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Audiohub
          .container.nav-collapse
            %ul.nav
              %li= link_to "Users", users_path
              %li= link_to "Audios", audios_path
            - if user_signed_in?
              = "Logged in as #{current_user.name}"
              = link_to 'Edit profile', edit_user_registration_path, class: "btn"
              = link_to 'Logout', destroy_user_session_path, :method => :delete, class: "btn"
            - else
              = link_to 'Sign Up', new_user_registration_path, class: 'btn'
              = link_to 'Login', new_user_session_path, class: 'btn'


    .container

      .row
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :encrypted_password, :class => 'control-label'
    .controls
      = f.text_field :encrypted_password, :class => 'text_field'
  .control-group
    = f.label :reset_password_token, :class => 'control-label'
    .controls
      = f.text_field :reset_password_token, :class => 'text_field'
  .control-group
    = f.label :reset_password_sent_at, :class => 'control-label'
    .controls
      = f.text_field :reset_password_sent_at, :class => 'text_field'
  .control-group
    = f.label :remember_created_at, :class => 'control-label'
    .controls
      = f.text_field :remember_created_at, :class => 'text_field'
  .control-group
    = f.label :current_sign_in_at, :class => 'control-label'
    .controls
      = f.text_field :current_sign_in_at, :class => 'text_field'
  .control-group
    = f.label :last_sign_in_at, :class => 'control-label'
    .controls
      = f.text_field :last_sign_in_at, :class => 'text_field'
  .control-group
    = f.label :current_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :current_sign_in_ip, :class => 'text_field'
  .control-group
    = f.label :last_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :last_sign_in_ip, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:encrypted_password)
      %th= model_class.human_attribute_name(:reset_password_token)
      %th= model_class.human_attribute_name(:reset_password_sent_at)
      %th= model_class.human_attribute_name(:remember_created_at)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:current_sign_in_ip)
      %th= model_class.human_attribute_name(:last_sign_in_ip)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.name
        %td= user.email
        %td= user.encrypted_password
        %td= user.reset_password_token
        %td= user.reset_password_sent_at
        %td= user.remember_created_at
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
          = link_to "Add Friend", friendships_path(:friend_id => user), :method => :post

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'